# Generated by Django 3.2.14 on 2022-08-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='title',
            field=models.CharField(max_length=20, unique=True, verbose_name='북마크 이름'),
        ),
    ]
